---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: "sub1-cicd-odf-02cd"
  drPolicyRef:
    name: drpolicy1
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox_app1
